analytics: {}
color:
  brandColors:
    - '#ef5a20'
    - '#fcfcf4'
    - '#f9a61a'
    - '#3298a6'
    - '#323d43'
  brandStrength: 0.521396
  lightness: 0.652027
  rhythmicContrast: 0.510135
  saturation: 0.286036
cta: {}
layout_spectrum: 0.24417
name: Kentico
opengraph: {}
purpose: []
typography_spectrum: 0.738738
