name: Kentico
favicon: null
layout_spectrum: 0.84395
typography_spectrum: 0.9067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ef5a20'
    - '#fcfcf4'
    - '#f9a61a'
    - '#3298a6'
    - '#323d43'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
